{% set version = '1.4-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spacesxyz
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spacesXYZ_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spacesXYZ/spacesXYZ_{{ version }}.tar.gz
  sha256: c7a4ea70bb081c2633ad77b897db17257c76303d94f8fd1ceed732e299f4d624

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-logger
  run:
    - r-base
    - r-logger

test:
  commands:
    - $R -e "library('spacesXYZ')"           # [not win]
    - "\"%R%\" -e \"library('spacesXYZ')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=spacesXYZ
  license: GPL-3.0-or-later
  summary: Functions for converting among CIE XYZ, xyY, Lab, and Luv. Calculate Correlated Color
    Temperature (CCT) and the Planckian and daylight loci. The XYZs of some standard
    illuminants and some standard linear chromatic adaptation transforms (CATs) are
    included. Three standard color difference metrics are included.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
